### ISSUE TITLE
Grey Out Pod in App When Appropriate (see ticket for details)

### ISSUE THREAD

**Issue by titapa-punpun** [titapapunne/MoreThanWords#110]
Two Cases of greying out a Pod:
- Case 1: Pod doesn't exist (i.e. there is no pod map attached to that user in SF)
   What the app should do: the Pod must be greyed out and should not be clickable
- Case 2: Youth hasn't unlocked the Pod
   What the app should do: the Pod should be greyed out but should still be clickable so that they can look through the tasks

**Comment by jchin01** [comment]
If the Pod doesn't exist it should not be clickable. This is different from when they haven't reached a pod but the pod exists
