### ISSUE TITLE
Create a New User Page

### ISSUE THREAD

**Issue by jchin01** [titapapunne/MoreThanWords#14]
### Ticket
 As a youth, I want to be able to register for the app if I am not already a user.

### Acceptance Criteria
Given I want to use the app, when I tap on the "Don't have an account? Sign up"  button, then it should take me to this page where I can be prompted to enter my information to verify that I can use this app/register with the MTW Salesforce Database

### Subtasks
* Write an endpoint that will check that the given email is registered with the MTW Slaesforce database
* If the user isn't already in the database, let them know that they cannot be registered to use the app

### Technical Specifications
Things to include on the registration page:
- Potentially 3 text boxes with email, name (first and last), D.O.B, and other identifying information to verify that it is actually them 

-  Verify that they do not already have an existing account

- After a successful registration, they should be redirected to home page

**Comment by titapa-punpun** [comment]
Closing this ticket because this will be handled by auth0
