### ISSUE TITLE
Reset Password Prompt Page

### ISSUE THREAD

**Issue by jchin01** [titapapunne/MoreThanWords#15]
### Ticket
As a youth, I want to be able to reset my password if I have forgotten it.

### Acceptance Criteria 
Given I want to use the app, when I want to tap on the "Forgot Password?", then I am redirected to a new page to reset my password.

### Subtasks
- Potential subtasks that may be an extension of this is to have an email reset system
     - figure out how to send the email (using what email? what API?)

### Details: Technical Specifications
Things to include on the reset page:
- Enter the email address to reset the password.
- Need to figure how to generate a unique password reset link that expires after a certain time and/or if the link has already been used.

**Comment by titapa-punpun** [comment]
An option for API sending emails: https://sendgrid.com/docs/for-developers/sending-email/ 
Will need to verify if Salesforce have this feature. If they do, it'll be easier for us to integrate using theirs.

**Comment by waymao** [comment]
Auth0 provides a password reset page. Can we use theirs for now?

**Comment by titapa-punpun** [comment]
Closing this because it'll be handled by auth0
