### ISSUE TITLE
Create Progress Bars for Pods (on Home Screen)

### ISSUE THREAD

**Issue by jchin01** [titapapunne/MoreThanWords#18]
### Ticket
As a youth, I want to see a 'Outcomes Achieved' progress bar for each of the 3 Pods, so that it is obvious to me which Pod(s) I've completed, which Pod I'm currently in, and which Pod(s) I have left to finish, as well as how much work I have left to do to complete each Pod's assigned outcomes.

### Acceptance Criteria 
Given I'm on the home screen, when I look at each of the 3 Pods displaying, then I see a progress bar for how I'm doing with the outcomes for each Pod.

### Subtasks:
- Endpoint creation
- Call to the different endpoints that show the total amount of completion of the focus ares, outcomes, and tasks

### Technical Specifications:
- A progress bar that will change as tasks are finished (maybe look into Native Base framework for progress bar UI)
- The progress should be based on the total percentage that is completed in the focus area, which looks at the percentage completion of the outcomes, which is based on the number of tasks.

<img width="105" alt="image" src="https://user-images.githubusercontent.com/29684577/95505777-ef480000-097c-11eb-9543-438cab2bc4e0.png">

<img width="527" alt="image" src="https://user-images.githubusercontent.com/29684577/95505756-e7885b80-097c-11eb-9901-9f43d8161db8.png">

**Comment by titapa-punpun** [comment]
Files downloaded from Salesforce (i.e. contains data in Salesforce):

[associate_pod_map__c_describe.xlsx](https://github.com/JumboCode/MoreThanWords/files/5380385/associate_pod_map__c_describe.xlsx)
[trainee_pod_map__c_describe.xlsx](https://github.com/JumboCode/MoreThanWords/files/5380386/trainee_pod_map__c_describe.xlsx)
