### ISSUE TITLE
Create Pod Screen

### ISSUE THREAD

**Issue by jchin01** [titapapunne/MoreThanWords#19]
### Ticket
As a youth, I want to see a pod screen for the corresponding Pod that I clicked on, so that I can look at my progress for that particular Pod's 3 focus areas.

### Acceptance Criteria 
- Given I've tapped on a the Trainee Pod from the home screen, when the Pod Screen launches, then I see that I'm on the Trainee Pod screen with the 3 focus areas, each of which I can click on.
- Given I've tapped on the Associate Pod from the home screen, when the Pod Screen launces, then I see that I'm on the Associate Pod screen with the 3 focus areas, each of which I can click on.
- Given I've tapped on the Partner Pod from the home screen, when the Pod Screen launches, then I see that I'm on the Partner Pod screen with 3 focus areas, each of which I can click on.

### Subtasks
- Each pod is potentially it's own react native component
- Routing in react native

### Technical Specifications
- Create the three components for each corresponding pod
- Route each pod to the correct page

**Comment by titapa-punpun** [comment]
Files downloaded from Salesforce (i.e. contains data in Salesforce):

[associate_pod_map__c_describe.xlsx](https://github.com/JumboCode/MoreThanWords/files/5380385/associate_pod_map__c_describe.xlsx)
[trainee_pod_map__c_describe.xlsx](https://github.com/JumboCode/MoreThanWords/files/5380386/trainee_pod_map__c_describe.xlsx)
