### ISSUE TITLE
Calculate Progress Bars for Trainee Pod's Focus Areas (on Pod Screen)

### ISSUE THREAD

**Issue by titapa-punpun** [titapapunne/MoreThanWords#20]
### Ticket
As a youth, I want to see a progress bar and # of outcomes achieved for each of the Trainee Pod's Focus Areas, so that I can visually and mathematically know what my progress for each Focus Area of the Trainee Pod is.

### Acceptance Criteria 
Given I'm on the Home Screen, when I click on the Trainee Pod, then I see a progress bar under each Focus Area name, and a "x out of y Outcomes Achieved" under each progress bar.

### Technical Specifications
- Backend: For each calculation, use a nominator and denominator. Then scale it to Native Base's progress bar calculation. 

### # of Outcomes for Trainee Pod
* Competencies: **3** total outcomes
* Career Exploration: **2** total outcomes
* Life Essentials & Support Network: **2** total outcomes

**Comment by jchin01** [comment]
TO-DO: write endpoint to fetch the total tasks and total completed tasks without hardcoding it
